### ISSUE TITLE
Do /run_code & /run_file messages still work (SP v3.1.0)?

### ISSUE THREAD

**Issue by ben-alkov** [SunderB/sb-atom-sonic-pi#1]
I'm interested in trying to set up something like this for VSCode.
I don't see those two commands when grepping through the SP v3.1.0 code base. There *is* `/save-and-run-buffer`...
Commands found (just for kicks :P)

```
/buffer-beautify
/buffer-section-complete-snippet-or-indent-selection
/buffer-section-toggle-comment
/check-for-updates-now
/delete-recording
/disable-update-checking
/enable-update-checking
/exit
# /gui-heartbeat
/load-buffer
/midi-reset
/midi-start
/midi-stop
/mixer-amp
/mixer-hpf-disable
/mixer-hpf-enable
/mixer-invert-stereo
/mixer-lpf-disable
/mixer-lpf-enable
/mixer-mono-mode
/mixer-standard-stereo
/mixer-stereo-mode
/osc-port-start
/osc-port-stop
/ping
/reload
/save-and-run-buffer
/save-buffer
/save-recording
/start-recording
/stop-all-jobs
/stop-recording
/version
```

**Comment by SunderB** [comment]
It seems like `/run-code` isn't used by the Sonic Pi GUI at the moment, but is still a valid osc command at the moment, so no need to worry 🙂 :
[samaaron/sonic-pi/app/server/ruby/bin/sonic-pi-server.rb - line 203](https://github.com/samaaron/sonic-pi/blob/1f346e7a6c3b1d9f833a0165101141622587b381/app/server/ruby/bin/sonic-pi-server.rb#L203)
```
osc_server.add_method("/run-code") do |args|
  gui_id = args[0]
  code = args[1].force_encoding("utf-8")
  sp.__spider_eval code
end
```

`run-file` isn't an osc command, it's a Sonic Pi function.
`@send('/run-code', 'atom', "run_file \"" + fullPath + "\"");` sends the osc command `/run-code` with the agent name (we're just using 'atom' for now), and the Sonic Pi code `run_file "fullPath"` where `fullPath` is the full file name. I hope this clears things up for you 🙂

**Comment by ben-alkov** [comment]
Man. I don't know how I missed that...
Thanks for the update!
