### ISSUE TITLE
Everything seems to work except sounds!! 

### ISSUE THREAD

**Issue by Etol1LC** [SunderB/sb-atom-sonic-pi#3]
Installed a few min ago. Everything seems to work. Sonic Pi receives osc msg when sending code from Atom(shows them in Cue log). No sound whatsoever. I am probably missing something crucial.

**Comment by SunderB** [comment]
Hi @Etol1LC :)
I've very recently released a new version which has some updates to make it work with newer versions of Sonic Pi (i.e. new default port numbers). I've managed to get it working on Debian with Sonic Pi v3.3
Try updating to the new version and see if it works :)

**Comment by SunderB** [comment]
Since it's been a year, I'm closing this issue for now. If you're still having problems feel free to reopen this or make a new issue. :)
