### ISSUE TITLE
Issue loading custom synth

### ISSUE THREAD

**Issue by twilightcourier** [SunderB/sb-atom-sonic-pi#4]
I have a custom synth I wanted to use in Sonic Pi. 
The following code runs in Sonic Pi.

```
load_synthdefs "C:/Users/twilightcourier/Downloads/test"
use_synth :rhodes
play note: 60, vel: 0.2
```

However, when run from atom I get the following error

```
Runtime Error: [buffer eval, line 3] - RuntimeError
Thread death!
 Unknown synth :rhodes
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:1068:in `synth'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:1193:in `play'
eval:3:in `block (2 levels) in __spider_eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:830:in `eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:830:in `block (2 levels) in __spider_eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:1093:in `block (2 levels) in __in_thread'
```

**Comment by SunderB** [comment]
Hi @twilightcourier :)
This is interesting... I don't see why this should happen exactly. Are you using the Play File (Alt+r) or Save and Play File (F5) command?

Could you tell me which version of Sonic Pi you're running? Also, are you able to share the synthdef file so I could test it?

**Comment by twilightcourier** [comment]
Thank you
For reporoducibility here is the Synthdef 
I found from this post https://in-thread.sonic-pi.net/t/modifying-and-compiling-synthdefs/2143/7
(
SynthDef(\rhodes, {
    |
    // standard meanings
    out_bus = 0, note = 70, amp = 1, out = 0, gate = 1, pan = 0,
    // all of these range from 0 to 1
    vel = 0.5, modIndex = 0.2, mix = 0.2, lfoSpeed = 0.4, lfoDepth = 0.1
    |
    var freq = note.midicps;
    var env1, env2, env3, env4;
    var osc1, osc2, osc3, osc4, snd;

    lfoSpeed = lfoSpeed * 12;

    freq = freq * 2;

    env1 = EnvGen.ar(Env.adsr(0.001, 1.25, 0.0, 0.04, curve: \lin));
    env2 = EnvGen.ar(Env.adsr(0.001, 1.00, 0.0, 0.04, curve: \lin));
    env3 = EnvGen.ar(Env.adsr(0.001, 1.50, 0.0, 0.04, curve: \lin));
    env4 = EnvGen.ar(Env.adsr(0.001, 1.50, 0.0, 0.04, curve: \lin));

    osc4 = SinOsc.ar(freq * 0.5) * 2pi * 2 * 0.535887 * modIndex * env4 * vel;
    osc3 = SinOsc.ar(freq, osc4) * env3 * vel;
    osc2 = SinOsc.ar(freq * 15) * 2pi * 0.108819 * env2 * vel;
    osc1 = SinOsc.ar(freq, osc2) * env1 * vel;
    snd = Mix((osc3 * (1 - mix)) + (osc1 * mix));
    snd = snd * (SinOsc.ar(lfoSpeed) * lfoDepth + 1);

    // using the doneAction: 2 on the other envs can create clicks (bc of the linear curve maybe?)
    snd = snd * EnvGen.ar(Env.asr(0, 1, 0.1), gate, doneAction: 2);
    snd = Pan2.ar(snd, pan, amp);

    Out.ar(out_bus, snd);
}).writeDefFile("C:/Users/twilightcourier/Downloads/test".standardizePath)
)


load_synthdefs "C:/Users/twilightcourier/Downloads/test"
use_synth :rhodes
play note: 60, vel: 0.2

I asked about this on the forum and it got resolved with this

load_synthdefs "C:/Users/twilightcourier/Downloads/test"
__thread_locals.set(:sonic_pi_mod_sound_use_external_synths, true)

use_synth :rhodes
play note: 60, vel: 0.2

to use the thread that controls external synths.

Using external synths i'm still having trouble playing chords/multiple notes at the same time though.

**Comment by twilightcourier** [comment]
load_synthdefs "C:\\Users\\twilightcourier\\Downloads\\test"
__thread_locals.set(:sonic_pi_mod_sound_use_external_synths, true)

use_synth :rhodes


play chord(:E3, :minor)

Runtime Error: [buffer eval, line 7] - RuntimeError
Thread death!
 Unable to normalise argument with key :note and value (ring <SonicPi::Chord :E :minor [52, 55, 59])
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3361:in `rescue in block in normalise_args!'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3358:in `block in normalise_args!'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3326:in `each'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3326:in `normalise_args!'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3765:in `normalise_and_resolve_synth_args'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:3448:in `trigger_inst'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:1100:in `synth'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/lang/sound.rb:1195:in `play'
eval:7:in `block (2 levels) in __spider_eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:830:in `eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:830:in `block (2 levels) in __spider_eval'
C:/Program Files/Sonic Pi/app/server/ruby/lib/sonicpi/runtime.rb:1093:in `block (2 levels) in __in_thread'

**Comment by SunderB** [comment]
Hey @twilightcourier,
Sorry for taking so long to reply. I've recently updated the package to work with Sonic Pi v4.0, and I've got the synth to work using this code:
```ruby
__thread_locals.set(:sonic_pi_mod_sound_use_external_synths, true)
load_synthdefs "/home/sunder/Documents/Coding/Sonic-Pi/music/"
use_synth "rhodes"

play 60 # C
sleep 1
play 62 # D
sleep 1
play 64 # E
```

Maybe try updating Sonic Pi and the package (see https://github.com/SunderB/sb-atom-sonic-pi/wiki/Installation#manual-installation-latest-stable-version for details on installing the update) and see if it works now?

**Comment by SunderB** [comment]
I'll mark this as closed for now. If you still are having any issues, please feel free to reopen this. :)
